### PR TITLE
Initial setup for configure and removing jaspColumnEncoder as submodule

### LINKED ISSUE #1: error on install jaspResults
Hi, it looks like this cpp module is required for installing jaspResults in R - 
Would it be possible to convert jaspColumnEncoder into an R package so that it can be installed as a jasp submodule/dependency for jaspResults? 

This is the error I'm receiving:

```
* installing *source* package ‘jaspResults’ ...
** using staged installation
** libs
...
columnencoder.cpp:2:10: fatal error: jaspColumnEncoder/columnencoder.cpp: No such file or directory
    2 | #include "jaspColumnEncoder/columnencoder.cpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [lib/R/etc/Makeconf:177: columnencoder.o] Error 1
ERROR: compilation failed for package ‘jaspResults’

```

Thanks!

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/jaspColumnEncoder/issues/1

TODO:
- [x] Write configure.win that does the same as configure but for windows.
- [x] Create a basic github action that tries to install jaspResults on windows, macOS, and Ubuntu. This action should test that
  - [x] the automatic downloads works.
  - [x] ~~providing a custom location for jaspColumnEncoder through configure.args works.~~

@JorisGoosen any suggestions so far?

### CODE REVIEW

**Comment by JorisGoosen** [comment]
The code looks fine so far, not sure why you added:
```
#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif
```
Though?

**Comment by vandenman** [comment]
I think that happens automatically with the latest version of Rcpp when you do `Rcpp::compileAttributes()` (which is done by default if you build in RStudio).

Edit: yes that addition is autogenerated. I'm not sure if we need to change this for inside JASP, but if we do we could just undefined `RCPP_USE_GLOBAL_ROSTREAM`.

**Comment by vandenman** [comment]
Ok, so the GitHub actions part works as well. I don't think that it's necessary to add another action that verifies whether the downloads and all that works because:

1. Building with JASP should never use the download and instead specify a custom location for jaspResults
2. All unit tests will download jaspColumnEncoder on the fly through the configure script.

**Comment by vandenman** [comment]
Changes to the R and Rd files are just to satisfy the R CMD CHECK btw.

**Review by JorisGoosen — APPROVED** [review]
Just tested it in R on Windows and it works fine there, now I wait for the build of it in qtcreator, not that I expect anything to go wrong there.

**Comment by JorisGoosen** [comment]
Ooh ah, and maybe I should wait with merging this until  we release 0.16.1 and 0.16.2

**Comment by vandenman** [comment]
>  I wait for the build of it in qtcreator, not that I expect anything to go wrong there.

Probably you spotted this already, but when jaspResults becomes an R package we do need to set configure.vars so that we use the same jaspColumnEncoder as JASP does.

**Comment by JorisGoosen** [comment]
> > I wait for the build of it in qtcreator, not that I expect anything to go wrong there.

It seems to compile and work fine in Qtcreator as well, so this can be merged whenever advantageous.
 
> Probably you spotted this already, but when jaspResults becomes an R package we do need to set configure.vars so that we use the same jaspColumnEncoder as JASP does.

Aah yes, I had skimmed that comment in the configure, but this should be fairly easy to do right?
As in, it will usually be installed through `jaspTools` or something right? So we could theoretically even do that dynamically by looking up the used commit in `jasp-desktop` or just hardcode it.

And even, I think, we could just use the latest `master` commit as default because I honestly expect it to almost never change.

**Review by JorisGoosen — APPROVED** [review]

**Pull request merged**
